spring.application.name=document-service

server.port=8082

# AWS S3
aws.region=us-west-2
aws.bucketName=amzn-s3-document-management-service-bucket

# PostgreSQL Database
spring.datasource.url=jdbc:postgresql://localhost:5432/documentdb
spring.datasource.username=dms_user
spring.datasource.password=yourpassword
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Kafka Configurations
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=document-service-group
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.JsonSerializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.JJsonDeserializer
